package com.vote.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("sys_user", SysUser.class);// 用户
		arp.addMapping("sys_role", SysRole.class);// 角色
		arp.addMapping("sys_role_menu", SysRoleMenu.class);// 角色菜单
		arp.addMapping("sys_user_role", SysUserRole.class);// 角色
		arp.addMapping("sys_menu", SysMenu.class);// 菜单
		arp.addMapping("sys_login_info", SysLoginInfo.class);// 用户登陆信息
        arp.addMapping("sys_dict_detail", DictDetail.class);// 字典表
        arp.addMapping("sys_dict_index", DictIndex.class);// 字典索引
        arp.addMapping("wx_menu", WxMenu.class);// 微信菜单
        arp.addMapping("wx_menu_msg", WxMenuMsg.class);// 微信菜单图文列表
        arp.addMapping("wx_msg", WxMsg.class);// 图文消息
        arp.addMapping("wx_msg_type", WxMsgType.class);// 图文消息类型
        arp.addMapping("wx_reply", WxReply.class);// 自动回复
        arp.addMapping("wx_reply_msg", WxReplyMsg.class);// 自动回复消息
        arp.addMapping("users", Users.class);// 微信用户--会员
        arp.addMapping("user_scan_log", UserScanLog.class);// 扫描记录
        arp.addMapping("wx_user_msg", WxUserMsg.class);// 用户留言记录
        arp.addMapping("vote", Vote.class);// 活动管理
        arp.addMapping("vote_item", VoteItem.class);// 选项
        arp.addMapping("vote_item_img", VoteItemImg.class);// 选项
        arp.addMapping("vote_group", VoteGroup.class);// 分组
        arp.addMapping("vote_code", VoteCode.class);// 编号
        arp.addMapping("vote_data", VoteData.class);// 用户投票数据
        arp.addMapping("vote_log", VoteLog.class);// 访问日志
        arp.addMapping("vote_gift", VoteGift.class);// 礼物
        arp.addMapping("vote_pay", VotePay.class);// 支付
	}
}

